name: Deploy
env:
  GKE_DEVELOPER_ADVOCACY_SA: ${{ secrets.GKE_DEVELOPER_ADVOCACY_SA }}
  A: 'avariable'
  B: 'anothervariable'
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:



      - uses: joshlong/basic-app-github-action@main
        with:
          kubernetes-environment: 'A,B'
          gke-service-account-key: ${{secrets.GKE_DEVELOPER_ADVOCACY_SA}}
          gke-zone: 'us-east4'
          gke-cluster: 'joshlong'
          gke-project: 'joshlong'
          kubernetes-namespace: 'test-ns'
          exposed: true
          container: 'us-docker.pkg.dev/joshlong/developer-advocacy-artifact-registry/joshlong-site:latest'
